// <auto-generated />
using System;
using Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260331122310_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Backend.Models.Company", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("Id"));

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("company_name");

                    b.HasKey("Id");

                    b.ToTable("companies");
                });

            modelBuilder.Entity("Backend.Models.Role", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("Id"));

                    b.Property<int>("RoleName")
                        .HasColumnType("int")
                        .HasColumnName("role_name");

                    b.HasKey("Id");

                    b.ToTable("roles");
                });

            modelBuilder.Entity("Backend.Models.User", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("Id"));

                    b.Property<uint?>("AssignedVehicleId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("assigned_vehicle_id");

                    b.Property<uint?>("CompanyId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("company_id");

                    b.Property<string>("CriminalRecord")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("criminal_record");

                    b.Property<string>("DriverLicenseId")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("driver_license_id");

                    b.Property<decimal?>("DriverScore")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("driver_score");

                    b.Property<string>("DriverTripStatus")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("driver_trip_status");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("last_name");

                    b.Property<uint?>("ParentUserId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("parent_user_id");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("phone");

                    b.Property<uint>("RoleId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("role_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.Property<string>("TcIdentityNumber")
                        .HasMaxLength(11)
                        .HasColumnType("varchar(11)")
                        .HasColumnName("tc_identity_number");

                    b.HasKey("Id");

                    b.HasIndex("AssignedVehicleId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("ParentUserId");

                    b.HasIndex("RoleId");

                    b.ToTable("users");
                });

            modelBuilder.Entity("Backend.Models.Vehicle", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("Id"));

                    b.Property<decimal>("BaseRentPrice")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("base_rent_price");

                    b.Property<string>("BrandModel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("brand_model");

                    b.Property<decimal>("CapacityKg")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("capacity_kg");

                    b.Property<DateTime?>("CascoEndDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("casco_end_date");

                    b.Property<DateTime?>("CascoStartDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("casco_start_date");

                    b.Property<DateTime?>("InspectionEndDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("inspection_end_date");

                    b.Property<DateTime?>("InspectionStartDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("inspection_start_date");

                    b.Property<DateTime?>("InsuranceEndDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("insurance_end_date");

                    b.Property<DateTime?>("InsuranceStartDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("insurance_start_date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted");

                    b.Property<int>("NextMaintenanceKm")
                        .HasColumnType("int")
                        .HasColumnName("next_maintenance_km");

                    b.Property<string>("PlateNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("plate_number");

                    b.Property<string>("RegistrationNumber")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("registration_number");

                    b.Property<string>("VehicleType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("vehicle_type");

                    b.Property<int>("Year")
                        .HasColumnType("int")
                        .HasColumnName("year");

                    b.HasKey("Id");

                    b.ToTable("vehicles");
                });

            modelBuilder.Entity("Backend.Models.User", b =>
                {
                    b.HasOne("Backend.Models.Vehicle", "AssignedVehicle")
                        .WithMany()
                        .HasForeignKey("AssignedVehicleId");

                    b.HasOne("Backend.Models.Company", "Company")
                        .WithMany("Users")
                        .HasForeignKey("CompanyId");

                    b.HasOne("Backend.Models.User", "ParentUser")
                        .WithMany("ChildUsers")
                        .HasForeignKey("ParentUserId");

                    b.HasOne("Backend.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedVehicle");

                    b.Navigation("Company");

                    b.Navigation("ParentUser");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Backend.Models.Company", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Backend.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Backend.Models.User", b =>
                {
                    b.Navigation("ChildUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
